### ISSUE TITLE
Add exclude filter

### ISSUE THREAD

**Issue by Souleymane-T** [Netsach/concrete-datastore#106]
It would be useful to have an `exclude` filters to exclude certain values from the results.

Example:

`/api/v1.1/<model-name>/?status__exclude=FAILED`

This request will return every instance that does not have `FAILED` as `status` field

**Comment by KhaledBousrih** [comment]
The exclude filters should keep the same lookups as the regular filters (`__in`, `__range`, `__contains`, ...)

I suggest that we use the exclude filters by adding a negation mark in front of the filter lookup, for example:

- `status!=FAILED` will return all the objects with a status other that `FAILED`
- `status__in!=FAILED,ABORTED` will return all the objects with a status other that `FAILED` and `ABORTED`
- `creation_date__range!=date1,date2` will return all the objects that have been created before date1 or after date2

**Comment by Souleymane-T** [comment]
Done and available in version `1.37.0`
