### ISSUE TITLE
Add JSONField key filtering

### ISSUE THREAD

**Issue by Souleymane-T** [Netsach/concrete-datastore#78]
It should be possible to filter against JSONField data.  
For example with this data for a field called `data` and a model `MyModel`:

```json
{
  "data": {
    "name": "Concrete",
    "type": "python",
    "owner": "Netsach"
  }
}
```

We should be able to filter like so:

- `/api/v1.1/my-model/?data__name=Concrete`
- `/api/v1.1/my-model/?data__type=python`
- `/api/v1.1/my-model/?data__owner=Netsach`

**Comment by paschembri** [comment]
Does it mean that we can also perform the following queries : 

- `/api/v1.1/my-model/?data__name__icontains=python`
- `/api/v1.1/my-model/?data__price__gte=10`
- ....

**Comment by Souleymane-T** [comment]
Yes we should be able to use those kind of filter for a JSONField
